### ISSUE TITLE
Gun: streaming response body breaks with Tesla.Middleware.Timeout

### ISSUE THREAD

**Issue by feld** [elixir-tesla/tesla#709]
The Timeout middleware breaks the ability to read the stream and an error is thrown due to no case clause matching

```
** (CaseClauseError) no case clause matching: {:error, :recv_chunk_timeout}
    (tesla 1.11.0) lib/tesla/adapter/gun.ex:493: anonymous fn/2 in Tesla.Adapter.Gun.format_response/6
    (elixir 1.16.3) lib/stream.ex:1626: Stream.do_resource/5
    (elixir 1.16.3) lib/enum.ex:1560: Enum.reduce_into_protocol/3
    (elixir 1.16.3) lib/enum.ex:1544: Enum.into_protocol/2
    iex:4: (file)
    ```

**Comment by yordis** [comment]
Hey @feld do you have a code snippet I could use to replicate this? I am gonna give it a try

**Comment by mmacia** [comment]
Happens the same in Finch

```elixir
defmodule Fetcher do
  use Tesla

  plug Tesla.Middleware.Timeout, timeout: 5_000
  
  def fetch(url) do
    case get(url, opts: [adapter: [response: :stream]]) do
      {:ok, %Tesla.Env{body: body} = env} ->

        body
        |> Stream.each(&IO.inspect(&1))
        |> Stream.run()
        
        {:ok, ""}

      {:error, error} ->
        Logger.error("Error fetching #{url} (#{inspect(error)})")
        {:error, error}
    end
  end
end

Fetcher.fetch("https://google.com")
```

```
** (ArgumentError) task %Task{mfa: {:erlang, :apply, 2}, owner: #PID<0.1083.0>, pid: #PID<0.1084.0>, ref: #Reference<0.0.138627.231394655.2129985546.201318>} must be queried from the owner but was queried from #PID<0.715.0>
    (elixir 1.17.3) lib/task.ex:1338: Task.shutdown/2
    (tesla 1.14.1) lib/tesla/adapter/finch.ex:138: anonymous fn/4 in Tesla.Adapter.Finch.stream/3
    (elixir 1.17.3) lib/stream.ex:1820: Stream.do_unfold/4
    (elixir 1.17.3) lib/stream.ex:1891: Enumerable.Stream.do_each/4
    (elixir 1.17.3) lib/stream.ex:690: Stream.run/1
    iex:49: Fetcher.fetch/1
    iex:39: (file)
```
